/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SummarizeRouteImport } from './routes/summarize'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as AskRouteImport } from './routes/ask'
import { Route as IndexRouteImport } from './routes/index'

const SummarizeRoute = SummarizeRouteImport.update({
  id: '/summarize',
  path: '/summarize',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/quiz': typeof QuizRoute
  '/roadmap': typeof RoadmapRoute
  '/summarize': typeof SummarizeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/quiz': typeof QuizRoute
  '/roadmap': typeof RoadmapRoute
  '/summarize': typeof SummarizeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/quiz': typeof QuizRoute
  '/roadmap': typeof RoadmapRoute
  '/summarize': typeof SummarizeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ask' | '/quiz' | '/roadmap' | '/summarize'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ask' | '/quiz' | '/roadmap' | '/summarize'
  id: '__root__' | '/' | '/ask' | '/quiz' | '/roadmap' | '/summarize'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  QuizRoute: typeof QuizRoute
  RoadmapRoute: typeof RoadmapRoute
  SummarizeRoute: typeof SummarizeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/summarize': {
      id: '/summarize'
      path: '/summarize'
      fullPath: '/summarize'
      preLoaderRoute: typeof SummarizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  QuizRoute: QuizRoute,
  RoadmapRoute: RoadmapRoute,
  SummarizeRoute: SummarizeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
